# 配置应用服务器(Tomcat)
server:
  port: 1111   # HTTP端口

# 配置发现服务器(Discovery Server)
eureka:
  instance:
    hostname: localhost
  client: # 不是客户端，所以不注册自己
    registerWithEureka: false
    fetchRegistry: false

